[IMP] l10n_it_sdi_channel: Permettere di ricevere notifiche per la ricezione di fatture elettroniche o notifiche
SirTakobi/l10n-italy pull request #2
Opened 2022-06-17 12:25 UTC by SirTakobi

2022-06-24 05:53 UTC, eLBati requested changes

2022-06-24 05:53 UTC, eLBati commented on l10n_it_sdi_channel/models/fatturapa_attachment.py
> +    channel_id = fields.Many2one(
Non possiamo renderlo un related tramite `company_id` ed evitare di scriverlo nei vari posti?

https://github.com/SirTakobi/l10n-italy/pull/4

2022-07-25 15:43 UTC, SirTakobi commented on l10n_it_sdi_channel/models/fatturapa_attachment.py
> +    channel_id = fields.Many2one(
Ho mergiato la tua proposta e corretto l'errore che introduceva

2022-07-25 15:43 UTC, SirTakobi commented
Mi sposto in https://github.com/OCA/l10n-italy/pull/2884

2022-07-25 15:50 UTC, closed without merging