[IMP] l10n_it_sdi_channel: Un pulsante per validare e inviare a SdI
SirTakobi/l10n-italy pull request #5
Opened 2022-07-14 10:06 UTC by SirTakobi

2022-07-14 13:52 UTC, eLBati requested changes
I commit di traduzioni non saranno da includere in https://github.com/OCA/l10n-italy/pull/2810 giusto?

2022-07-14 13:52 UTC, eLBati commented on l10n_it_sdi_channel/views/company_view.xml
> +                                Allow users to validate, export and send invoices to SdI in one click.
Qui non è proprio "Allow users" perchè se faccio click qui sto abilitando il gruppo per me, quindi penso sia meglio solo "validate, export and send invoices to SdI in one click"

2022-07-14 13:52 UTC, eLBati commented on l10n_it_fatturapa_pec/tests/test_e_invoice_send.py
> +        self.assertEqual(e_invoice.state, 'sent')
Questo commit ha il nome del modulo sbagliato mi pare

2022-07-15 09:33 UTC, SirTakobi reviewed
> I commit di traduzioni non saranno da includere in https://github.com/OCA/l10n-italy/pull/2810 giusto?

Sì, se preferisci li sposto in un'altra PR

2022-07-15 09:33 UTC, SirTakobi commented on l10n_it_fatturapa_pec/tests/test_e_invoice_send.py
> +        self.assertEqual(e_invoice.state, 'sent')
Corretto, grazie

2022-07-15 09:33 UTC, SirTakobi commented on l10n_it_sdi_channel/views/company_view.xml
> +                                Allow users to validate, export and send invoices to SdI in one click.
I campi `group_XXX` aggiungono o tolgono il gruppo da quelli _implied_ di un altro gruppo, che di default (questo caso) è `base.group_user`: è spiegato in
> For a boolean field like 'group_XXX', ``execute`` adds/removes 'implied_group'
to/from the implied groups of 'group', depending on the field's value.
By default 'group' is the group Employee.  Groups are given by their xml id.
The attribute 'group' may contain several xml ids, separated by commas.

(rif. https://github.com/odoo/odoo/blob/9e9ac5ced80b30c9f091fed5d6ea9199786237d1/odoo/addons/base/models/res_config.py#L353-L356)

Quindi abilitando il flag, tutti gli utenti potranno Validare, ecc.

2022-07-15 09:51 UTC, eLBati commented on l10n_it_sdi_channel/views/company_view.xml
> +                                Allow users to validate, export and send invoices to SdI in one click.
grazie

2022-07-15 09:54 UTC, eLBati commented
> > I commit di traduzioni non saranno da includere in [OCA#2810](https://github.com/OCA/l10n-italy/pull/2810) giusto?
> 
> Sì, se preferisci li sposto in un'altra PR

Avendo fatto merge della https://github.com/OCA/l10n-italy/pull/2810 , direi di sì, così il target di questa PR può diventare `12.0`

2022-07-15 13:48 UTC, SirTakobi commented
> > > I commit di traduzioni non saranno da includere in [OCA#2810](https://github.com/OCA/l10n-italy/pull/2810) giusto?
> > 
> > 
> > Sì, se preferisci li sposto in un'altra PR
> 
> Avendo fatto merge della [OCA#2810](https://github.com/OCA/l10n-italy/pull/2810) , direi di sì, così il target di questa PR può diventare `12.0`

Spostate le traduzioni in https://github.com/SirTakobi/l10n-italy/pull/6

2022-07-18 08:05 UTC, SirTakobi commented
Fatto rebase, mi sposto su https://github.com/OCA/l10n-italy/pull/2876

2022-07-18 08:05 UTC, closed without merging